import {
  Compass,
  Camera,
  Landmark,
  UtensilsCrossed,
  Wallet,
  BookOpen,
  Map,
  Users,
  Flame,
  Gift,
  Award,
  Scale,
  Building2,
  Coffee,
  Wine,
  ShoppingBag,
  BedDouble,
  Ticket,
  Tag,
  Trees,
  Image as ImageIcon,
  MapPin,
  Trophy,
  Coins,
  Gamepad2,
  Home,
  Luggage,
  PenLine,
  HeartPulse,
  TrainFront,
  GraduationCap,
  Church,
  Calendar,
  Music,
  PartyPopper,
  MessageCircle,
  Crown,
  Sparkles,
  ShieldCheck,
  Send,
} from 'lucide-react'

// Système d'icônes unique pour tout le site : des traits simples
// (lucide-react), une seule couleur héritée du texte (currentColor),
// pas de pictogrammes multicolores. Les données (catégories, badges,
// types de commerce/lieu) stockent une clé sobre ("trophee",
// "restaurant"...) plutôt qu'un émoji -- ce composant fait la
// correspondance clé -> icône au moment de l'affichage.
const ICONES = {
  compass: Compass,
  camera: Camera,
  landmark: Landmark,
  restaurant: UtensilsCrossed,
  wallet: Wallet,
  livre: BookOpen,
  carte: Map,
  utilisateurs: Users,
  flamme: Flame,
  cadeau: Gift,
  recompense: Award,
  balance: Scale,
  batiment: Building2,
  cafe: Coffee,
  bar: Wine,
  boutique: ShoppingBag,
  hotel: BedDouble,
  ticket: Ticket,
  etiquette: Tag,
  parc: Trees,
  musee: ImageIcon,
  lieu: MapPin,
  trophee: Trophy,
  pieces: Coins,
  jeu: Gamepad2,
  maison: Home,
  valise: Luggage,
  plume: PenLine,
  hopital: HeartPulse,
  gare: TrainFront,
  ecole: GraduationCap,
  eglise: Church,
  calendrier: Calendar,
  musique: Music,
  fete: PartyPopper,
  message: MessageCircle,
  couronne: Crown,
  etincelle: Sparkles,
  bouclier: ShieldCheck,
  envoyer: Send,
}

export default function Icone({ nom, className = 'h-4 w-4', strokeWidth = 1.75 }) {
  const Cmp = ICONES[nom]
  if (!Cmp) return null
  return <Cmp className={className} strokeWidth={strokeWidth} aria-hidden="true" />
}
